controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AddBookForm;
use app\models\Authors;
use app\models\Books;
use app\models\Genre;
use app\models\Tags;
use app\models\Tags_relation;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\data\Pagination;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $request = Yii::$app->request;

        //Get books:
        $query = $request->get('genre') ?   : Books::find();
        if ($request->get('genre')) {
            $query = Books::find()->where(['genre_id' => $request->get('genre')]);
        }elseif ($request->get('tag')) {
            $query = Tags::findOne(['id' => $request->get('tag')])->getBooks();
        }elseif ($request->get('author')) {
            $query = Authors::findOne(['id' => $request->get('author')])->getBooks();
        } else {
            $query = Books::find();
        }
        $count = is_array($query) ? count($query) : $query->count();
        $pagination = new Pagination ([
            'defaultPageSize' => 5,
            'totalCount' => $count,
        ]);

        $order = $request->get('order') ?: 'id';
        $books = $query -> orderBy($order)
            -> offset($pagination->offset)    //Query of teams table
            -> limit ($pagination->limit)
            -> all();

        //Get Genres
        $genres = Genre::find()->orderBy('id')->all();

        //Get Tags
        $tags = Tags::find()->orderBy('id')->all();

        //Get Authors
        $authors = Authors::find()->orderBy('name')->all();

        return $this -> render('index', [
            'books' => $books,
            'pagination' => $pagination,
            'genres' => $genres,
            'tags' => $tags,
            'authors' => $authors,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionBook()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $request = Yii::$app->request;
        $book = Books::findOne($request->get('id'));
        $author = Authors::findOne($book['author_id']);
        $genre = Genre::findOne($book['genre_id']);
        $tags = $book->getTags()->all();

        return $this->render('book', [
            'book' => $book,
            'author' => $author,
            'genre' => $genre,
            'tags' => $tags,
        ]) ;
    }

    public function actionAddBook()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        $form = new AddBookForm();

        if (Yii::$app->request->isPost) {
            if ($form->load(Yii::$app->request->post())) {
                $form->poster = UploadedFile::getInstance($form, 'poster');
                $poster = $form->upload();

                // Write book to DB
                $book = new Books();
                $book->title = $form->title;
                $book->description = $form->description;
                $book->author_id = $form->author_id;
                $book->genre_id = $form->genre_id;
                $book->poster = $poster;
                $book->save();

                // Record Tags
                $tags = Yii::$app->request->post('AddBookForm')['tags'];
                foreach ($tags as $tag) {
                    $record = new Tags_relation();
                    $record->tag_id = $tag;
                    $record->book_id = $book->id;
                    $record->save();
                }

                return $this->redirect(['site/index']);
            }
        }

        $authors = Authors::find()->select(['name', 'id'])->indexBy('id')->column();
        $genres = Genre::find()->select(['title', 'id'])->indexBy('id')->column();
        $tags = Tags::find()->select(['title', 'id'])->indexBy('id')->column();
        return $this->render('addBook', [
            'model' => $form,
            'authors' => $authors,
            'genres' => $genres,
            'tags' => $tags,
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/addBook.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;

$this->title = 'Add new book';
?>

<h1><?= $this->title ?></h1>

<?php $form = ActiveForm::begin([
    'method' => 'post',
    'options' => ['enctype' => 'multipart/form-data'],
    'action' => Url::to(['site/add-book']),
]) ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'description') ?>
<?= $form->field($model, 'genre_id')->dropdownList(
    $genres, ['prompt'=>'Select Genre']);
?>
<?= $form->field($model, 'author_id')->dropdownList(
    $authors, ['prompt'=>'Select Author']);
?>
<?= $form->field($model, 'tags[]')->checkboxList($tags)->label('Tags:') ?>
<?= $form->field($model, 'poster')->fileInput() ?>
<?= Html::submitButton('Add book', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

views/site/book.php
<?php
/* @var $this yii\web\View */

$this->title = $book['title'];
?>
<div class="row">
    <div class="col-md-9">
        <div class="jumbotron mb-3">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="<?= $book['poster'] ?>" class="card-img" alt="<?= $book['title'] ?>">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><?= $book['title'] ?></h5>
                        <p class="card-text"><?= $book['description'] ?></p>
                        <a class="btn btn-info" href="<?= Yii::$app->homeUrl . '?author=' . $author['id'] ?>"><?= $author['name'] ?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="alert alert-danger">Genre:
            <a class="btn btn-warning" href="<?= Yii::$app->homeUrl . '?genre=' . $genre['id'] ?>"><?= $genre['title'] ?></a>
        </div>
        <!--Tags:        -->
        <div class="alert alert-success">Tags:</div>
        <div>
            <?php foreach ($tags as $tag):?>
                <a class="btn btn-success" href="<?= Yii::$app->homeUrl . '?tag=' . $tag['id'] ?>"><?= $tag['title'] ?></a>
            <?php endforeach;?>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

$this->title = 'Books library';
?>
    <h1>Books Library</h1>
<div class="row">
    <div class="col-md-9">
        <!--Genres:        -->
        <div class="d-flex justify-content-between">
            <div class="alert alert-danger">Genres:
                <?php foreach ($genres as $genre):?>
                    <a class="btn btn-warning" href="<?= Yii::$app->homeUrl . '?genre=' . $genre['id'] ?>"><?= $genre['title'] ?></a>
                <?php endforeach;?>
            </div>
        </div>

        <!--Books:-->
        <!--Order by        -->
        <div class="">
            <span class="bg-success">Order by:</span>
            <a class="badge badge-dark" href="<?= Yii::$app->homeUrl . '?order=title' ?>">title</a>
            <a class="badge badge-dark" href="<?= Yii::$app->homeUrl . '?order=id' ?>">id</a>
        </div>
            <div class="card-deck">
            <?php foreach ($books as $book):?>
                <a href="<?= \yii\helpers\Url::to(['site/book', 'id' => $book['id']]); ?>">
                    <div class="card">
                        <img src="<?= $book['poster'] ?>" class="card-img-top" alt="<?= $book['title'] ?>">
                        <div class="card-body">
                            <h5 class="card-title"><?= $book['title'] ?></h5>
                            <p class="card-text"><?= substr($book['description'], 0, 100) . '...' ?></p>
                        </div>
                    </div>
                </a>
            <?php endforeach;?>
            </div>
            <?php echo \yii\bootstrap4\LinkPager::widget([
                'pagination' => $pagination,
            ]);?>
    </div>
    <div class="col-md-3">
        <a class="btn btn-danger" href="<?= \yii\helpers\Url::to(['site/add-book']); ?>">Add new book</a>
        <!--Tags:        -->
        <div class="alert alert-success">Tags:</div>
        <div>
            <?php foreach ($tags as $tag):?>
                <a class="btn btn-success" href="<?= Yii::$app->homeUrl . '?tag=' . $tag['id'] ?>"><?= $tag['title'] ?></a>
            <?php endforeach;?>
        </div>

        <!--Authors:        -->
        <div class="alert alert-info">Authors:</div>
        <div>
            <?php foreach ($authors as $author):?>
                <a class="btn btn-primary" href="<?= Yii::$app->homeUrl . '?author=' . $author['id'] ?>"><?= $author['name'] ?></a>
            <?php endforeach;?>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <h2>Please login to access the library:</h2>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>Login:</strong> vasia <strong>Password:</strong> pupkin
    </div>
</div>